require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./models/Question');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/quiz-app';

const rawData = [
{"id": 1,"chapter": "Weather and Climate","question": "What is weather?","options": ["Long-term condition", "Short-term atmospheric condition", "Climate zone", "Season"],"answer": "Short-term atmospheric condition"},
{"id": 2,"chapter": "Weather and Climate","question": "Climate is determined over how many years?","options": ["5–10", "10–20", "35–40", "50–100"],"answer": "35–40"},
{"id": 3,"chapter": "Weather and Climate","question": "Which is NOT an element of weather?","options": ["Temperature", "Pressure", "Humidity", "Latitude"],"answer": "Latitude"},
{"id": 4,"chapter": "Weather and Climate","question": "Main source of energy for Earth?","options": ["Moon", "Sun", "Wind", "Ocean"],"answer": "Sun"},
{"id": 5,"chapter": "Weather and Climate","question": "Insolation means:","options": ["Heat from earth", "Sunlight reaching Earth", "Cloud heat", "Ocean heat"],"answer": "Sunlight reaching Earth"},
{"id": 6,"chapter": "Weather and Climate","question": "Which process transfers heat vertically?","options": ["Advection", "Conduction", "Convection", "Radiation"],"answer": "Convection"},
{"id": 7,"chapter": "Weather and Climate","question": "Heat transfer horizontally is called:","options": ["Conduction", "Advection", "Radiation", "Fusion"],"answer": "Advection"},
{"id": 8,"chapter": "Weather and Climate","question": "Re-radiation from Earth is called:","options": ["Insolation", "Reflection", "Terrestrial radiation", "Fusion"],"answer": "Terrestrial radiation"},
{"id": 9,"chapter": "Weather and Climate","question": "Greenhouse effect is caused by:","options": ["Oxygen", "CO2", "Nitrogen", "Helium"],"answer": "CO2"},
{"id": 10,"chapter": "Weather and Climate","question": "Instrument to measure temperature?","options": ["Barometer", "Thermometer", "Hygrometer", "Anemometer"],"answer": "Thermometer"},
{"id": 11,"chapter": "Weather and Climate","question": "Unit of temperature?","options": ["Joule", "Celsius", "Pascal", "Meter"],"answer": "Celsius"},
{"id": 12,"chapter": "Weather and Climate","question": "Diurnal range is:","options": ["Average temp", "Max - Min temp", "Sum temp", "Night temp"],"answer": "Max - Min temp"},
{"id": 13,"chapter": "Weather and Climate","question": "Isotherms connect:","options": ["Pressure", "Wind", "Temperature", "Rainfall"],"answer": "Temperature"},
{"id": 14,"chapter": "Weather and Climate","question": "Temperature decreases towards:","options": ["Equator", "Poles", "Sea", "Desert"],"answer": "Poles"},
{"id": 15,"chapter": "Weather and Climate","question": "Thermal equator means:","options": ["Cold line", "Hottest region line", "Wind zone", "Pressure zone"],"answer": "Hottest region line"},
{"id": 16,"chapter": "Weather and Climate","question": "Normal lapse rate is:","options": ["3°C/km", "6.4°C/km", "10°C/km", "1°C/km"],"answer": "6.4°C/km"},
{"id": 17,"chapter": "Weather and Climate","question": "Higher altitude means:","options": ["Higher temp", "Lower temp", "No change", "Hot climate"],"answer": "Lower temp"},
{"id": 18,"chapter": "Weather and Climate","question": "Which area has high diurnal range?","options": ["Coastal", "Interior", "Forest", "Mountain"],"answer": "Interior"},
{"id": 19,"chapter": "Weather and Climate","question": "Warm current example:","options": ["Labrador", "Gulf Stream", "Canary", "None"],"answer": "Gulf Stream"},
{"id": 20,"chapter": "Weather and Climate","question": "Cold current example:","options": ["Gulf Stream", "Labrador", "Monsoon", "Trade wind"],"answer": "Labrador"},
{"id": 21,"chapter": "Weather and Climate","question": "Instrument to measure pressure?","options": ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],"answer": "Barometer"},
{"id": 22,"chapter": "Weather and Climate","question": "Average pressure:","options": ["500 mb", "1013 mb", "2000 mb", "50 mb"],"answer": "1013 mb"},
{"id": 23,"chapter": "Weather and Climate","question": "Isobars connect:","options": ["Temp", "Pressure", "Wind", "Humidity"],"answer": "Pressure"},
{"id": 24,"chapter": "Weather and Climate","question": "Low pressure forms due to:","options": ["Cold air", "Hot air rises", "Wind stops", "Rainfall"],"answer": "Hot air rises"},
{"id": 25,"chapter": "Weather and Climate","question": "Winds blow from:","options": ["Low to high", "High to low", "Sea to sun", "None"],"answer": "High to low"},
{"id": 26,"chapter": "Weather and Climate","question": "Coriolis effect deflects wind:","options": ["Straight", "Right (NH)", "Left (NH)", "Upward"],"answer": "Right (NH)"},
{"id": 27,"chapter": "Weather and Climate","question": "Trade winds blow from:","options": ["Equator to poles", "Subtropical to equator", "Poles to equator", "Sea to land"],"answer": "Subtropical to equator"},
{"id": 28,"chapter": "Weather and Climate","question": "Doldrums are:","options": ["High pressure", "Low pressure calm zone", "Windy zone", "Cold zone"],"answer": "Low pressure calm zone"},
{"id": 29,"chapter": "Weather and Climate","question": "Monsoon means:","options": ["Rainfall", "Wind reversal", "Storm", "Cloud"],"answer": "Wind reversal"},
{"id": 30,"chapter": "Weather and Climate","question": "Sea breeze blows:","options": ["Land to sea", "Sea to land", "Upward", "Downward"],"answer": "Sea to land"},
{"id": 31,"chapter": "Weather and Climate","question": "Humidity is:","options": ["Heat", "Water vapour", "Wind", "Pressure"],"answer": "Water vapour"},
{"id": 32,"chapter": "Weather and Climate","question": "Instrument for humidity:","options": ["Barometer", "Hygrometer", "Thermometer", "Anemometer"],"answer": "Hygrometer"},
{"id": 33,"chapter": "Weather and Climate","question": "Condensation means:","options": ["Gas to liquid", "Liquid to gas", "Solid to gas", "Heat"],"answer": "Gas to liquid"},
{"id": 34,"chapter": "Weather and Climate","question": "Rainfall is:","options": ["Condensation", "Precipitation", "Evaporation", "Humidity"],"answer": "Precipitation"},
{"id": 35,"chapter": "Weather and Climate","question": "Rain shadow area:","options": ["Windward", "Leeward", "Sea", "Forest"],"answer": "Leeward"},
{"id": 36,"chapter": "Climatic Regions","question": "Climatic region means:","options": ["Small area", "Similar climate area", "Cold place", "Dry place"],"answer": "Similar climate area"},
{"id": 37,"chapter": "Climatic Regions","question": "Equatorial region rainfall:","options": ["Low", "Moderate", "High", "None"],"answer": "High"},
{"id": 38,"chapter": "Climatic Regions","question": "Equatorial climate temp:","options": ["Low", "Moderate", "High", "Variable"],"answer": "High"},
{"id": 39,"chapter": "Climatic Regions","question": "Monsoon climate depends on:","options": ["Rainfall only", "Wind reversal", "Temperature only", "Altitude"],"answer": "Wind reversal"},
{"id": 40,"chapter": "Climatic Regions","question": "Savanna climate:","options": ["Dry only", "Wet & dry", "Cold", "Snow"],"answer": "Wet & dry"},
{"id": 41,"chapter": "Climatic Regions","question": "Hot deserts:","options": ["High rainfall", "Low rainfall", "Cold", "Snow"],"answer": "Low rainfall"},
{"id": 42,"chapter": "Climatic Regions","question": "Mediterranean climate:","options": ["Dry winter", "Wet winter", "Snow", "Hot all year"],"answer": "Wet winter"},
{"id": 43,"chapter": "Climatic Regions","question": "Tundra region:","options": ["Hot", "Cold", "Wet", "Dry"],"answer": "Cold"},
{"id": 44,"chapter": "Climatic Regions","question": "Taiga region vegetation:","options": ["Grass", "Evergreen forest", "Desert", "None"],"answer": "Evergreen forest"},
{"id": 45,"chapter": "Climatic Regions","question": "Equatorial forest type:","options": ["Deciduous", "Evergreen", "Grassland", "Shrub"],"answer": "Evergreen"},
{"id": 46,"chapter": "Consumer Rights","question": "Consumer means:","options": ["Seller", "Buyer", "Producer", "Trader"],"answer": "Buyer"},
{"id": 47,"chapter": "Consumer Rights","question": "Right to safety protects from:","options": ["Loss", "Dangerous goods", "Price rise", "Tax"],"answer": "Dangerous goods"},
{"id": 48,"chapter": "Consumer Rights","question": "Right to information:","options": ["Buy freely", "Know details", "Sell goods", "None"],"answer": "Know details"},
{"id": 49,"chapter": "Consumer Rights","question": "Consumer court deals with:","options": ["Criminal", "Consumer issues", "Civil", "None"],"answer": "Consumer issues"},
{"id": 50,"chapter": "Consumer Rights","question": "ISI mark indicates:","options": ["Price", "Quality assurance", "Weight", "Brand name"],"answer": "Quality assurance"},
{"id": 51,"chapter": "Consumer Rights","question": "Consumer Protection Act was passed in India in:","options": ["1986", "1991", "2000", "2010"],"answer": "1986"},
{"id": 52,"chapter": "Consumer Rights","question": "Right to be heard ensures:","options": ["Free goods", "Complaint consideration", "Low price", "Discount"],"answer": "Complaint consideration"},
{"id": 53,"chapter": "Consumer Rights","question": "Right to seek redressal means:","options": ["Buy goods", "Get compensation", "Sell goods", "None"],"answer": "Get compensation"},
{"id": 54,"chapter": "Consumer Rights","question": "Right to choose means:","options": ["Buy any product freely", "Limited options", "Forced buying", "None"],"answer": "Buy any product freely"},
{"id": 55,"chapter": "Money and Economy","question": "Money is used as:","options": ["Only exchange", "Medium of exchange", "Only savings", "None"],"answer": "Medium of exchange"},
{"id": 56,"chapter": "Money and Economy","question": "Barter system means:","options": ["Money use", "Goods exchange", "Banking", "Saving"],"answer": "Goods exchange"},
{"id": 57,"chapter": "Money and Economy","question": "Main drawback of barter:","options": ["Storage", "Double coincidence", "Transport", "None"],"answer": "Double coincidence"},
{"id": 58,"chapter": "Money and Economy","question": "Modern money includes:","options": ["Coins only", "Notes and coins", "Gold only", "Goods"],"answer": "Notes and coins"},
{"id": 59,"chapter": "Money and Economy","question": "Bank function:","options": ["Printing money", "Deposits & loans", "Selling goods", "Transport"],"answer": "Deposits & loans"},
{"id": 60,"chapter": "Money and Economy","question": "Cheque is:","options": ["Cash", "Credit instrument", "Goods", "Coin"],"answer": "Credit instrument"},
{"id": 61,"chapter": "Money and Economy","question": "ATM stands for:","options": ["Automatic Transfer Machine", "Automated Teller Machine", "Auto Trade Machine", "None"],"answer": "Automated Teller Machine"},
{"id": 62,"chapter": "Money and Economy","question": "Inflation means:","options": ["Price fall", "Price rise", "No change", "Saving"],"answer": "Price rise"},
{"id": 63,"chapter": "Money and Economy","question": "Central bank of India:","options": ["SBI", "RBI", "ICICI", "PNB"],"answer": "RBI"},
{"id": 64,"chapter": "Money and Economy","question": "Digital payment example:","options": ["Cash", "UPI", "Barter", "Gold"],"answer": "UPI"},
{"id": 65,"chapter": "Climatic Regions","question": "Equatorial region location:","options": ["0–10° N/S", "20–30°", "40–50°", "60–70°"],"answer": "0–10° N/S"},
{"id": 66,"chapter": "Climatic Regions","question": "Equatorial rainfall type:","options": ["Orographic", "Cyclonic", "Convectional", "None"],"answer": "Convectional"},
{"id": 67,"chapter": "Climatic Regions","question": "Monsoon winds blow:","options": ["Constant", "Seasonal reversal", "Random", "Cold"],"answer": "Seasonal reversal"},
{"id": 68,"chapter": "Climatic Regions","question": "Savanna vegetation:","options": ["Forest", "Grassland", "Desert", "Ice"],"answer": "Grassland"},
{"id": 69,"chapter": "Climatic Regions","question": "Hot desert example:","options": ["Sahara", "Amazon", "Arctic", "Taiga"],"answer": "Sahara"},
{"id": 70,"chapter": "Climatic Regions","question": "Mediterranean crops:","options": ["Rice", "Wheat", "Olives", "Maize"],"answer": "Olives"},
{"id": 71,"chapter": "Climatic Regions","question": "Tundra vegetation:","options": ["Trees", "Grass", "Moss", "Forest"],"answer": "Moss"},
{"id": 72,"chapter": "Climatic Regions","question": "Taiga region temp:","options": ["Hot", "Moderate", "Cold", "Dry"],"answer": "Cold"},
{"id": 73,"chapter": "Climatic Regions","question": "Equatorial tribes:","options": ["Eskimos", "Pygmies", "Arabs", "Indians"],"answer": "Pygmies"},
{"id": 74,"chapter": "Climatic Regions","question": "Monsoon region example:","options": ["India", "Canada", "USA", "Russia"],"answer": "India"},
{"id": 75,"chapter": "Weather and Climate","question": "Clouds form due to:","options": ["Evaporation", "Condensation", "Wind", "Heat"],"answer": "Condensation"},
{"id": 76,"chapter": "Weather and Climate","question": "Cirrus clouds:","options": ["Low", "High altitude", "Rain clouds", "Dense"],"answer": "High altitude"},
{"id": 77,"chapter": "Weather and Climate","question": "Nimbus clouds:","options": ["Dry", "Rain-bearing", "Cold", "Thin"],"answer": "Rain-bearing"},
{"id": 78,"chapter": "Weather and Climate","question": "Cumulus clouds:","options": ["Flat", "Cotton-like", "Thin", "Dark"],"answer": "Cotton-like"},
{"id": 79,"chapter": "Weather and Climate","question": "Stratus clouds:","options": ["Layered", "Vertical", "Thin", "Hot"],"answer": "Layered"},
{"id": 80,"chapter": "Weather and Climate","question": "Snowfall occurs when:","options": ["Hot", "Below 0°C", "Rain", "Wind"],"answer": "Below 0°C"},
{"id": 81,"chapter": "Weather and Climate","question": "Hailstones are:","options": ["Water drops", "Ice pellets", "Gas", "Dust"],"answer": "Ice pellets"},
{"id": 82,"chapter": "Weather and Climate","question": "Orographic rainfall occurs at:","options": ["Desert", "Mountains", "Sea", "Forest"],"answer": "Mountains"},
{"id": 83,"chapter": "Weather and Climate","question": "Convectional rainfall occurs due to:","options": ["Wind", "Heating", "Cold air", "Pressure"],"answer": "Heating"},
{"id": 84,"chapter": "Weather and Climate","question": "Cyclonic rainfall occurs when:","options": ["Hot meets hot", "Cold meets cold", "Warm meets cold", "Dry meets dry"],"answer": "Warm meets cold"},
{"id": 85,"chapter": "Weather and Climate","question": "Cloudburst means:","options": ["Low rain", "Heavy rain", "No rain", "Wind"],"answer": "Heavy rain"},
{"id": 86,"chapter": "Weather and Climate","question": "Fog forms at:","options": ["Upper atmosphere", "Lower atmosphere", "Space", "Sea"],"answer": "Lower atmosphere"},
{"id": 87,"chapter": "Weather and Climate","question": "Dew forms at:","options": ["Day", "Night", "Afternoon", "Evening"],"answer": "Night"},
{"id": 88,"chapter": "Weather and Climate","question": "Frost occurs when:","options": ["Above 0°C", "Below 0°C", "Rain", "Heat"],"answer": "Below 0°C"},
{"id": 89,"chapter": "Weather and Climate","question": "Relative humidity unit:","options": ["°C", "mb", "%", "m"],"answer": "%"},
{"id": 90,"chapter": "General","question": "Which sector deals with climate?","options": ["Economics", "Geography", "History", "Politics"],"answer": "Geography"},
{"id": 91,"chapter": "General","question": "Which affects human life most?","options": ["Weather", "Climate", "Wind", "Rain"],"answer": "Climate"},
{"id": 92,"chapter": "General","question": "Best rainfall for agriculture:","options": ["None", "Moderate", "Heavy", "Low"],"answer": "Moderate"},
{"id": 93,"chapter": "General","question": "Wind speed measured by:","options": ["Barometer", "Anemometer", "Hygrometer", "Thermometer"],"answer": "Anemometer"},
{"id": 94,"chapter": "General","question": "Wind direction measured by:","options": ["Anemometer", "Wind vane", "Barometer", "Thermometer"],"answer": "Wind vane"},
{"id": 95,"chapter": "General","question": "Atmosphere mainly contains:","options": ["Oxygen", "Nitrogen", "CO2", "Helium"],"answer": "Nitrogen"},
{"id": 96,"chapter": "General","question": "Main greenhouse gas:","options": ["Oxygen", "CO2", "Nitrogen", "Hydrogen"],"answer": "CO2"},
{"id": 97,"chapter": "General","question": "Climate change cause:","options": ["Natural only", "Human only", "Both", "None"],"answer": "Both"},
{"id": 98,"chapter": "General","question": "Global warming means:","options": ["Cooling", "Temperature rise", "Rainfall", "Wind"],"answer": "Temperature rise"},
{"id": 99,"chapter": "General","question": "Ozone layer protects from:","options": ["Rain", "UV rays", "Wind", "Heat"],"answer": "UV rays"},
{"id": 100,"chapter": "General","question": "Sustainable development means:","options": ["Use resources freely", "Use without harming future", "No use", "Overuse"],"answer": "Use without harming future"},
{ "id": 101, "chapter": "Weather and Climate", "question": "Why does temperature decrease from equator to poles?", "options": ["Distance from sea", "Inclined sun rays", "Wind speed", "Rainfall"], "answer": "Inclined sun rays" },
{ "id": 102, "chapter": "Weather and Climate", "question": "Which factor causes low temperature in mountains?", "options": ["Latitude", "Altitude", "Humidity", "Wind"], "answer": "Altitude" },
{ "id": 103, "chapter": "Weather and Climate", "question": "Why coastal areas have moderate climate?", "options": ["Wind speed", "Sea influence", "Altitude", "Pressure"], "answer": "Sea influence" },
{ "id": 104, "chapter": "Weather and Climate", "question": "Interior regions show high diurnal range due to:", "options": ["Sea breeze", "Lack of water bodies", "Clouds", "Rainfall"], "answer": "Lack of water bodies" },
{ "id": 105, "chapter": "Weather and Climate", "question": "Which current makes Europe warmer?", "options": ["Labrador", "Canary", "Gulf Stream", "Monsoon"], "answer": "Gulf Stream" },
{ "id": 106, "chapter": "Weather and Climate", "question": "Low pressure areas are associated with:", "options": ["Descending air", "Rising air", "Cold air", "Dry air"], "answer": "Rising air" },
{ "id": 107, "chapter": "Weather and Climate", "question": "High pressure areas have:", "options": ["Rising air", "Descending air", "Warm air", "Clouds"], "answer": "Descending air" },
{ "id": 108, "chapter": "Weather and Climate", "question": "Humidity reduces atmospheric pressure because:", "options": ["Air becomes heavier", "Air becomes lighter", "No change", "Wind increases"], "answer": "Air becomes lighter" },
{ "id": 109, "chapter": "Weather and Climate", "question": "Pressure gradient controls:", "options": ["Rainfall", "Wind speed", "Humidity", "Clouds"], "answer": "Wind speed" },
{ "id": 110, "chapter": "Weather and Climate", "question": "Frictional force affects:", "options": ["Temperature", "Wind movement", "Humidity", "Rainfall"], "answer": "Wind movement" },
{ "id": 111, "chapter": "Weather and Climate", "question": "Trade winds are deflected due to:", "options": ["Pressure", "Coriolis force", "Temperature", "Humidity"], "answer": "Coriolis force" },
{ "id": 112, "chapter": "Weather and Climate", "question": "Westerlies blow between:", "options": ["Equator & 30°", "30° & 60°", "60° & poles", "Poles & equator"], "answer": "30° & 60°" },
{ "id": 113, "chapter": "Weather and Climate", "question": "Polar winds originate from:", "options": ["Equator", "Subtropics", "Poles", "Sea"], "answer": "Poles" },
{ "id": 114, "chapter": "Weather and Climate", "question": "ITCZ is:", "options": ["High pressure", "Low pressure convergence zone", "Wind zone", "Cold zone"], "answer": "Low pressure convergence zone" },
{ "id": 115, "chapter": "Weather and Climate", "question": "Why ITCZ shifts?", "options": ["Earth rotation", "Sun movement", "Wind speed", "Rainfall"], "answer": "Sun movement" },
{ "id": 116, "chapter": "Weather and Climate", "question": "Sea breeze occurs during:", "options": ["Night", "Day", "Winter", "Rain"], "answer": "Day" },
{ "id": 117, "chapter": "Weather and Climate", "question": "Land breeze occurs during:", "options": ["Day", "Night", "Summer", "Winter"], "answer": "Night" },
{ "id": 118, "chapter": "Weather and Climate", "question": "Mountain breeze flows:", "options": ["Upward", "Downward", "Sea to land", "Land to sea"], "answer": "Downward" },
{ "id": 119, "chapter": "Weather and Climate", "question": "Valley breeze flows:", "options": ["Downward", "Upward", "Sea to land", "None"], "answer": "Upward" },
{ "id": 120, "chapter": "Weather and Climate", "question": "Which is a local wind?", "options": ["Trade wind", "Westerlies", "Loo", "Polar wind"], "answer": "Loo" },
{ "id": 121, "chapter": "Weather and Climate", "question": "Cyclones are:", "options": ["High pressure", "Low pressure systems", "Cold systems", "Dry systems"], "answer": "Low pressure systems" },
{ "id": 122, "chapter": "Weather and Climate", "question": "Cyclones rotate anticlockwise in:", "options": ["Southern Hemisphere", "Northern Hemisphere", "Equator", "Ocean"], "answer": "Northern Hemisphere" },
{ "id": 123, "chapter": "Weather and Climate", "question": "Anticyclones are:", "options": ["Low pressure", "High pressure", "Storms", "Rainfall"], "answer": "High pressure" },
{ "id": 124, "chapter": "Weather and Climate", "question": "Humidity is maximum at:", "options": ["Desert", "Equator", "Poles", "Mountains"], "answer": "Equator" },
{ "id": 125, "chapter": "Weather and Climate", "question": "Relative humidity at saturation:", "options": ["50%", "75%", "100%", "0%"], "answer": "100%" },
{ "id": 126, "chapter": "Weather and Climate", "question": "Dew forms when:", "options": ["Cooling at night", "Heating", "Wind", "Rain"], "answer": "Cooling at night" },
{ "id": 127, "chapter": "Weather and Climate", "question": "Fog reduces:", "options": ["Humidity", "Visibility", "Temperature", "Pressure"], "answer": "Visibility" },
{ "id": 128, "chapter": "Weather and Climate", "question": "Clouds form around:", "options": ["Water", "Dust particles", "Wind", "Heat"], "answer": "Dust particles" },
{ "id": 129, "chapter": "Weather and Climate", "question": "Rainfall occurs when droplets:", "options": ["Become lighter", "Become heavier", "Disappear", "Heat"], "answer": "Become heavier" },
{ "id": 130, "chapter": "Weather and Climate", "question": "Which rainfall occurs in mountains?", "options": ["Cyclonic", "Convectional", "Orographic", "None"], "answer": "Orographic" },
{ "id": 131, "chapter": "Climatic Regions", "question": "Equatorial climate has:", "options": ["Low rainfall", "High rainfall", "Cold weather", "Snow"], "answer": "High rainfall" },
{ "id": 132, "chapter": "Climatic Regions", "question": "Savanna region has:", "options": ["Only rain", "Wet and dry seasons", "Snow", "Cold"], "answer": "Wet and dry seasons" },
{ "id": 133, "chapter": "Climatic Regions", "question": "Desert climate has:", "options": ["High rainfall", "Low rainfall", "Moderate rain", "Snow"], "answer": "Low rainfall" },
{ "id": 134, "chapter": "Climatic Regions", "question": "Mediterranean climate has:", "options": ["Dry summer", "Wet summer", "Snow all year", "None"], "answer": "Dry summer" },
{ "id": 135, "chapter": "Climatic Regions", "question": "Tundra climate is:", "options": ["Hot", "Cold", "Wet", "Dry"], "answer": "Cold" },
{ "id": 136, "chapter": "Consumer Rights", "question": "Right to information helps in:", "options": ["Selling goods", "Knowing product details", "Buying cheap", "None"], "answer": "Knowing product details" },
{ "id": 137, "chapter": "Consumer Rights", "question": "Consumer courts ensure:", "options": ["Profit", "Justice", "Trade", "Marketing"], "answer": "Justice" },
{ "id": 138, "chapter": "Consumer Rights", "question": "Right to safety protects against:", "options": ["High price", "Unsafe goods", "Taxes", "Trade"], "answer": "Unsafe goods" },
{ "id": 139, "chapter": "Consumer Rights", "question": "Right to redressal means:", "options": ["Buying", "Selling", "Compensation", "None"], "answer": "Compensation" },
{ "id": 140, "chapter": "Consumer Rights", "question": "Consumer awareness leads to:", "options": ["Loss", "Protection", "Fraud", "Risk"], "answer": "Protection" },
{ "id": 141, "chapter": "Money and Economy", "question": "Money helps in:", "options": ["Exchange", "Production", "Consumption", "All"], "answer": "All" },
{ "id": 142, "chapter": "Money and Economy", "question": "Bank gives loans for:", "options": ["Consumption", "Investment", "Savings", "None"], "answer": "Investment" },
{ "id": 143, "chapter": "Money and Economy", "question": "Inflation reduces:", "options": ["Price", "Value of money", "Income", "Savings"], "answer": "Value of money" },
{ "id": 144, "chapter": "Money and Economy", "question": "Digital economy uses:", "options": ["Cash only", "Online payments", "Barter", "Gold"],"answer": "Online payments" },
{ "id": 145, "chapter": "Money and Economy", "question": "RBI controls:", "options": ["Weather", "Economy", "Climate", "Trade"], "answer": "Economy" },
{ "id": 146, "chapter": "General", "question": "Global warming increases:", "options": ["Cold", "Temperature", "Snow", "Wind"], "answer": "Temperature" },
{ "id": 147, "chapter": "General", "question": "Deforestation causes:", "options": ["Cooling", "Warming", "Rainfall", "Snow"], "answer": "Warming" },
{ "id": 148, "chapter": "General", "question": "Sustainable use means:", "options": ["Overuse", "Future protection", "No use", "Waste"], "answer": "Future protection" },
{ "id": 149, "chapter": "General", "question": "Climate change affects:", "options": ["Humans", "Animals", "Plants", "All"], "answer": "All" },
{"id": 150,"chapter": "General","question": "Best way to reduce climate change:","options": ["Pollution", "Conservation", "Deforestation", "Overuse"],"answer": "Conservation"},
{ "id": 151, "chapter": "Weather and Climate", "question": "Why do deserts have extreme temperatures?", "options": ["High rainfall", "Lack of humidity", "Cloud cover", "Ocean currents"], "answer": "Lack of humidity" },
{ "id": 152, "chapter": "Weather and Climate", "question": "Which factor reduces temperature variation in coastal areas?", "options": ["Altitude", "Sea influence", "Latitude", "Pressure"], "answer": "Sea influence" },
{ "id": 153, "chapter": "Weather and Climate", "question": "Why does hot air rise?", "options": ["Becomes heavier", "Becomes lighter", "Wind pressure", "Gravity"], "answer": "Becomes lighter" },
{ "id": 154, "chapter": "Weather and Climate", "question": "What causes wind movement?", "options": ["Humidity", "Pressure difference", "Clouds", "Rainfall"], "answer": "Pressure difference" },
{ "id": 155, "chapter": "Weather and Climate", "question": "Why do mountains receive more rainfall?", "options": ["Cold air", "Orographic lifting", "Wind speed", "Humidity"], "answer": "Orographic lifting" },
{ "id": 156, "chapter": "Weather and Climate", "question": "Which region receives convectional rainfall?", "options": ["Desert", "Equatorial", "Polar", "Tundra"], "answer": "Equatorial" },
{ "id": 157, "chapter": "Weather and Climate", "question": "Cyclones bring:", "options": ["Dry weather", "Heavy rainfall", "Cold air", "Dust"], "answer": "Heavy rainfall" },
{ "id": 158, "chapter": "Weather and Climate", "question": "Anticyclones bring:", "options": ["Rain", "Clear weather", "Storm", "Humidity"], "answer": "Clear weather" },
{ "id": 159, "chapter": "Weather and Climate", "question": "Why is equatorial region humid?", "options": ["Cold air", "High evaporation", "Low rainfall", "Wind"], "answer": "High evaporation" },
{ "id": 160, "chapter": "Weather and Climate", "question": "Cloud formation requires:", "options": ["Dust particles", "Wind", "Heat", "Pressure"], "answer": "Dust particles" },
{ "id": 161, "chapter": "Climatic Regions", "question": "Which region has evergreen forests?", "options": ["Desert", "Equatorial", "Tundra", "Savanna"], "answer": "Equatorial" },
{ "id": 162, "chapter": "Climatic Regions", "question": "Savanna region supports:", "options": ["Dense forests", "Grasslands", "Ice", "Deserts"], "answer": "Grasslands" },
{ "id": 163, "chapter": "Climatic Regions", "question": "Hot deserts have:", "options": ["Heavy rainfall", "Sparse vegetation", "Dense forest", "Snow"], "answer": "Sparse vegetation" },
{ "id": 164, "chapter": "Climatic Regions", "question": "Mediterranean climate supports:", "options": ["Rice", "Olives", "Wheat only", "None"], "answer": "Olives" },
{ "id": 165, "chapter": "Climatic Regions", "question": "Tundra region has:", "options": ["Trees", "Grass", "Moss", "Crops"], "answer": "Moss" },
{ "id": 166, "chapter": "Consumer Rights", "question": "Which right protects from unfair trade?", "options": ["Right to choose", "Right to safety", "Right to information", "Right to be heard"], "answer": "Right to safety" },
{ "id": 167, "chapter": "Consumer Rights", "question": "Consumer awareness helps to:", "options": ["Increase fraud", "Avoid exploitation", "Raise price", "Reduce trade"], "answer": "Avoid exploitation" },
{ "id": 168, "chapter": "Consumer Rights", "question": "ISI mark ensures:", "options": ["Low price", "Quality", "Weight", "Tax"], "answer": "Quality" },
{ "id": 169, "chapter": "Consumer Rights", "question": "Complaint can be filed in:", "options": ["Police", "Court", "Consumer forum", "School"], "answer": "Consumer forum" },
{ "id": 170, "chapter": "Consumer Rights", "question": "Right to redressal ensures:", "options": ["Profit", "Justice", "Trade", "Loss"], "answer": "Justice" },
{ "id": 171, "chapter": "Money and Economy", "question": "Money solves barter problem of:", "options": ["Storage", "Double coincidence", "Transport", "Trade"], "answer": "Double coincidence" },
{ "id": 172, "chapter": "Money and Economy", "question": "Banks promote:", "options": ["Trade", "Savings", "Loans", "All"], "answer": "All" },
{ "id": 173, "chapter": "Money and Economy", "question": "Inflation affects:", "options": ["Value of money", "Climate", "Wind", "Rain"], "answer": "Value of money" },
{ "id": 174, "chapter": "Money and Economy", "question": "Digital payment reduces:", "options": ["Cash use", "Trade", "Savings", "Economy"], "answer": "Cash use" },
{ "id": 175, "chapter": "Money and Economy", "question": "Central bank controls:", "options": ["Trade", "Money supply", "Weather", "Climate"], "answer": "Money supply" },
{ "id": 176, "chapter": "General", "question": "Global warming causes:", "options": ["Cooling", "Sea level rise", "Snowfall", "Wind"], "answer": "Sea level rise" },
{ "id": 177, "chapter": "General", "question": "Deforestation leads to:", "options": ["Cooling", "Soil erosion", "Rainfall increase", "Snow"], "answer": "Soil erosion" },
{ "id": 178, "chapter": "General", "question": "Sustainable development focuses on:", "options": ["Present only", "Future only", "Both present & future", "None"], "answer": "Both present & future" },
{ "id": 179, "chapter": "General", "question": "Climate change affects agriculture by:", "options": ["Increasing yield always", "Unpredictable rainfall", "Reducing soil", "None"], "answer": "Unpredictable rainfall" },
{ "id": 180, "chapter": "General", "question": "Best solution for pollution:", "options": ["Increase use", "Reduce use", "Ignore", "Destroy"], "answer": "Reduce use" },
{ "id": 181, "chapter": "Case Based", "question": "A farmer in desert faces water shortage. Reason?", "options": ["High rainfall", "Low rainfall", "Humidity", "Wind"], "answer": "Low rainfall" },
{ "id": 182, "chapter": "Case Based", "question": "Coastal farmer gets stable yield because:", "options": ["Extreme climate", "Moderate climate", "Low rainfall", "Cold weather"], "answer": "Moderate climate" },
{ "id": 183, "chapter": "Case Based", "question": "A buyer gets defective product. What should he do?", "options": ["Ignore", "Return", "File complaint", "Sell"], "answer": "File complaint" },
{ "id": 184, "chapter": "Case Based", "question": "A person uses UPI instead of cash. Reason?", "options": ["Slow", "Fast & easy", "Costly", "Difficult"], "answer": "Fast & easy" },
{ "id": 185, "chapter": "Case Based", "question": "Heavy rainfall in mountains occurs due to:", "options": ["Cyclone", "Orographic effect", "Humidity", "Wind"], "answer": "Orographic effect" },
{ "id": 186, "chapter": "Case Based", "question": "A region with grassland and seasonal rain is:", "options": ["Desert", "Savanna", "Tundra", "Polar"], "answer": "Savanna" },
{ "id": 187, "chapter": "Case Based", "question": "A consumer checks ISI mark before buying. Why?", "options": ["Cheap", "Quality", "Brand", "Weight"], "answer": "Quality" },
{ "id": 188, "chapter": "Case Based", "question": "A rise in price reduces value of money. This is:", "options": ["Deflation", "Inflation", "Depression", "Growth"], "answer": "Inflation" },
{ "id": 189, "chapter": "Case Based", "question": "A region with snow and moss vegetation is:", "options": ["Savanna", "Tundra", "Desert", "Equatorial"], "answer": "Tundra" },
{ "id": 190, "chapter": "Case Based", "question": "Wind blowing from high to low pressure shows:", "options": ["Humidity", "Pressure gradient", "Rainfall", "Heat"], "answer": "Pressure gradient" },
{ "id": 191, "chapter": "Case Based", "question": "A cyclone warning is issued. Expected condition?", "options": ["Clear sky", "Heavy rain & wind", "Cold", "Dry"], "answer": "Heavy rain & wind" },
{ "id": 192, "chapter": "Case Based", "question": "A desert has sparse vegetation due to:", "options": ["Cold", "Low rainfall", "Wind", "Humidity"], "answer": "Low rainfall" },
{ "id": 193, "chapter": "Case Based", "question": "A student studies climate science. Subject?", "options": ["Economics", "Geography", "History", "Math"], "answer": "Geography" },
{ "id": 194, "chapter": "Case Based", "question": "A person saves money in bank. Purpose?", "options": ["Loss", "Security", "Waste", "Trade"], "answer": "Security" },
{ "id": 195, "chapter": "Case Based", "question": "A forest cut leads to climate change. Why?", "options": ["Less oxygen", "More oxygen", "No effect", "Cooling"], "answer": "Less oxygen" },
{ "id": 196, "chapter": "Case Based", "question": "A region receives heavy daily rainfall. Climate?", "options": ["Desert", "Equatorial", "Tundra", "Polar"], "answer": "Equatorial" },
{ "id": 197, "chapter": "Case Based", "question": "A person buys product without checking details. Which right ignored?", "options": ["Safety", "Information", "Choice", "Redressal"], "answer": "Information" },
{ "id": 198, "chapter": "Case Based", "question": "A hot wind in North India is:", "options": ["Loo", "Chinook", "Foehn", "Monsoon"], "answer": "Loo" },
{ "id": 199, "chapter": "Case Based", "question": "A rise in sea level affects:", "options": ["Mountains", "Coastal areas", "Deserts", "Forests"], "answer": "Coastal areas" },
{"id": 200,"chapter": "Case Based","question": "Using resources wisely is called:","options": ["Overuse", "Sustainability", "Pollution", "Waste"],"answer": "Sustainability"},
{ "id": 201, "chapter": "Assertion-Reason", "question": "Assertion (A): Coastal areas have moderate climate. Reason (R): Water heats and cools slowly.", "options": ["Both true & R explains A", "Both true but R not explanation", "A true R false", "A false R true"], "answer": "Both true & R explains A" },
{ "id": 202, "chapter": "Assertion-Reason", "question": "A: Deserts have low humidity. R: They receive very low rainfall.", "options": ["Both true & R explains A", "Both true not explanation", "A true R false", "A false R true"], "answer": "Both true & R explains A" },
{ "id": 203, "chapter": "Assertion-Reason", "question": "A: Winds move from high to low pressure. R: Pressure gradient force exists.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 204, "chapter": "Assertion-Reason", "question": "A: Equatorial regions are hot. R: Sun rays fall vertically.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 205, "chapter": "Assertion-Reason", "question": "A: Mountains are cooler. R: Temperature decreases with altitude.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 206, "chapter": "Assertion-Reason", "question": "A: Cyclones bring rainfall. R: They are low-pressure systems.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 207, "chapter": "Assertion-Reason", "question": "A: Anticyclones bring clear weather. R: They are high-pressure systems.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 208, "chapter": "Assertion-Reason", "question": "A: Fog reduces visibility. R: It forms near ground level.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 209, "chapter": "Assertion-Reason", "question": "A: Dew forms at night. R: Temperature drops.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 210, "chapter": "Assertion-Reason", "question": "A: Clouds form by condensation. R: Water vapour cools and changes state.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 211, "chapter": "HOTS", "question": "Why are equatorial regions densely forested?", "options": ["Low rainfall", "High rainfall & temperature", "Cold weather", "Wind"], "answer": "High rainfall & temperature" },
{ "id": 212, "chapter": "HOTS", "question": "Why do deserts have sparse population?", "options": ["High rainfall", "Lack of water", "Cold", "Forests"], "answer": "Lack of water" },
{ "id": 213, "chapter": "HOTS", "question": "Why Mediterranean regions grow olives?", "options": ["Cold weather", "Dry summers", "Snow", "Rain"], "answer": "Dry summers" },
{ "id": 214, "chapter": "HOTS", "question": "Why tundra has no trees?", "options": ["High rainfall", "Frozen soil", "Hot climate", "Wind"], "answer": "Frozen soil" },
{ "id": 215, "chapter": "HOTS", "question": "Why savanna supports grazing?", "options": ["Forest", "Grasslands", "Desert", "Snow"], "answer": "Grasslands" },
{ "id": 216, "chapter": "HOTS", "question": "Why consumers need awareness?", "options": ["To spend more", "To avoid exploitation", "To trade", "To produce"], "answer": "To avoid exploitation" },
{ "id": 217, "chapter": "HOTS", "question": "Why digital payments are increasing?", "options": ["Slow", "Convenient", "Expensive", "Difficult"], "answer": "Convenient" },
{ "id": 218, "chapter": "HOTS", "question": "Why inflation is harmful?", "options": ["Raises value", "Reduces purchasing power", "Increases savings", "None"], "answer": "Reduces purchasing power" },
{ "id": 219, "chapter": "HOTS", "question": "Why banks are important?", "options": ["Store goods", "Provide financial services", "Transport", "Weather"], "answer": "Provide financial services" },
{ "id": 220, "chapter": "HOTS", "question": "Why money replaced barter?", "options": ["Easy exchange", "Complex", "Heavy", "Risky"], "answer": "Easy exchange" },
{ "id": 221, "chapter": "Application", "question": "A city near sea has stable weather. Reason?", "options": ["Altitude", "Sea effect", "Wind", "Rain"], "answer": "Sea effect" },
{ "id": 222, "chapter": "Application", "question": "A desert farmer uses drip irrigation. Why?", "options": ["More water", "Save water", "Cheap", "Wind"], "answer": "Save water" },
{ "id": 223, "chapter": "Application", "question": "A consumer files case for defect. Which right?", "options": ["Safety", "Information", "Redressal", "Choice"], "answer": "Redressal" },
{ "id": 224, "chapter": "Application", "question": "A person uses ATM for withdrawal. Advantage?", "options": ["Slow", "Quick access", "Costly", "Risky"], "answer": "Quick access" },
{ "id": 225, "chapter": "Application", "question": "A rise in CO2 leads to:", "options": ["Cooling", "Global warming", "Rain", "Wind"], "answer": "Global warming" },
{ "id": 226, "chapter": "Application", "question": "A mountain region gets heavy rain. Why?", "options": ["Cyclone", "Orographic effect", "Wind", "Heat"], "answer": "Orographic effect" },
{ "id": 227, "chapter": "Application", "question": "A person compares products before buying. Which right?", "options": ["Choice", "Safety", "Information", "Redressal"], "answer": "Choice" },
{ "id": 228, "chapter": "Application", "question": "A bank gives loan for business. Purpose?", "options": ["Saving", "Investment", "Loss", "Waste"], "answer": "Investment" },
{ "id": 229, "chapter": "Application", "question": "A cyclone warning issued. Action?", "options": ["Ignore", "Prepare", "Travel", "Sleep"], "answer": "Prepare" },
{ "id": 230, "chapter": "Application", "question": "A rise in sea level affects:", "options": ["Mountains", "Coastal areas", "Deserts", "Forests"], "answer": "Coastal areas" },
{ "id": 231, "chapter": "Mixed", "question": "Which gas causes global warming?", "options": ["Oxygen", "CO2", "Nitrogen", "Hydrogen"], "answer": "CO2" },
{ "id": 232, "chapter": "Mixed", "question": "Which region is coldest?", "options": ["Desert", "Equator", "Tundra", "Savanna"], "answer": "Tundra" },
{ "id": 233, "chapter": "Mixed", "question": "Which climate has wet winters?", "options": ["Desert", "Mediterranean", "Tundra", "Savanna"], "answer": "Mediterranean" },
{ "id": 234, "chapter": "Mixed", "question": "Which instrument measures wind speed?", "options": ["Barometer", "Anemometer", "Thermometer", "Hygrometer"], "answer": "Anemometer" },
{ "id": 235, "chapter": "Mixed", "question": "Which is a greenhouse gas?", "options": ["Oxygen", "CO2", "Nitrogen", "Helium"], "answer": "CO2" },
{ "id": 236, "chapter": "Mixed", "question": "Which bank controls Indian economy?", "options": ["SBI", "RBI", "ICICI", "PNB"], "answer": "RBI" },
{ "id": 237, "chapter": "Mixed", "question": "Which region gets heavy rainfall daily?", "options": ["Desert", "Equatorial", "Tundra", "Savanna"], "answer": "Equatorial" },
{ "id": 238, "chapter": "Mixed", "question": "Which wind is local?", "options": ["Trade wind", "Westerlies", "Loo", "Polar wind"], "answer": "Loo" },
{ "id": 239, "chapter": "Mixed", "question": "Which system gives justice to consumers?", "options": ["Police", "Court", "Consumer forum", "School"], "answer": "Consumer forum" },
{ "id": 240, "chapter": "Mixed", "question": "Which process forms clouds?", "options": ["Evaporation", "Condensation", "Heating", "Wind"], "answer": "Condensation" },
{ "id": 241, "chapter": "Mixed", "question": "Which rainfall type in equatorial region?", "options": ["Cyclonic", "Orographic", "Convectional", "None"], "answer": "Convectional" },
{ "id": 242, "chapter": "Mixed", "question": "Which climate is cold and dry?", "options": ["Desert", "Tundra", "Savanna", "Equatorial"], "answer": "Tundra" },
{ "id": 243, "chapter": "Mixed", "question": "Which economic system uses digital money?", "options": ["Barter", "Digital economy", "Traditional", "None"], "answer": "Digital economy" },
{ "id": 244, "chapter": "Mixed", "question": "Which right protects from unsafe goods?", "options": ["Choice", "Safety", "Information", "Redressal"], "answer": "Safety" },
{ "id": 245, "chapter": "Mixed", "question": "Which gas protects Earth from UV rays?", "options": ["CO2", "Ozone", "Oxygen", "Nitrogen"], "answer": "Ozone" },
{ "id": 246, "chapter": "Mixed", "question": "Which wind causes monsoon?", "options": ["Trade wind", "Seasonal wind", "Polar wind", "Local wind"], "answer": "Seasonal wind" },
{ "id": 247, "chapter": "Mixed", "question": "Which climate supports grassland?", "options": ["Savanna", "Desert", "Tundra", "Polar"], "answer": "Savanna" },
{ "id": 248, "chapter": "Mixed", "question": "Which rainfall occurs due to mountains?", "options": ["Cyclonic", "Orographic", "Convectional", "None"], "answer": "Orographic" },
{ "id": 249, "chapter": "Mixed", "question": "Which process forms dew?", "options": ["Evaporation", "Condensation", "Heating", "Wind"], "answer": "Condensation" },
{"id": 250,"chapter": "Mixed","question": "Which is best for environment?","options": ["Pollution", "Sustainability", "Overuse", "Waste"],"answer": "Sustainability"},
{ "id": 251, "chapter": "Assertion-Reason", "question": "A: Interior regions have extreme temperature. R: Lack of sea influence.", "options": ["Both true & R explains A", "Both true not explanation", "A true R false", "A false R true"], "answer": "Both true & R explains A" },
{ "id": 252, "chapter": "Assertion-Reason", "question": "A: Equatorial regions have daily rainfall. R: Strong convection currents.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 253, "chapter": "Assertion-Reason", "question": "A: Tundra has permafrost. R: Temperature remains below freezing.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 254, "chapter": "Assertion-Reason", "question": "A: Mediterranean climate has dry summers. R: Subtropical high pressure.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 255, "chapter": "Assertion-Reason", "question": "A: Monsoon winds change direction. R: Seasonal pressure changes.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 256, "chapter": "Assertion-Reason", "question": "A: Barter system failed. R: Double coincidence problem.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 257, "chapter": "Assertion-Reason", "question": "A: Inflation reduces purchasing power. R: Prices increase.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 258, "chapter": "Assertion-Reason", "question": "A: ISI mark ensures quality. R: It is a certification.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 259, "chapter": "Assertion-Reason", "question": "A: Consumer courts protect buyers. R: They solve disputes.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 260, "chapter": "Assertion-Reason", "question": "A: Global warming raises sea level. R: Ice melts.", "options": ["Both true & R explains A", "Both true not explanation", "A false R true", "A true R false"], "answer": "Both true & R explains A" },
{ "id": 261, "chapter": "HOTS", "question": "Why do polar regions remain cold?", "options": ["High humidity", "Low sun angle", "High rainfall", "Wind"], "answer": "Low sun angle" },
{ "id": 262, "chapter": "HOTS", "question": "Why do coastal cities rarely face extreme heat?", "options": ["Altitude", "Ocean currents", "Sea moderation", "Humidity"], "answer": "Sea moderation" },
{ "id": 263, "chapter": "HOTS", "question": "Why does heavy rainfall cause landslides?", "options": ["Dry soil", "Water saturation", "Wind", "Heat"], "answer": "Water saturation" },
{ "id": 264, "chapter": "HOTS", "question": "Why do deserts cool quickly at night?", "options": ["Clouds", "Low humidity", "Rainfall", "Wind"], "answer": "Low humidity" },
{ "id": 265, "chapter": "HOTS", "question": "Why is equatorial biodiversity high?", "options": ["Cold", "Stable climate", "Low rainfall", "Wind"], "answer": "Stable climate" },
{ "id": 266, "chapter": "HOTS", "question": "Why is consumer protection important?", "options": ["Increase price", "Prevent exploitation", "Reduce goods", "None"], "answer": "Prevent exploitation" },
{ "id": 267, "chapter": "HOTS", "question": "Why do people prefer banks?", "options": ["Risky", "Safe storage", "Slow", "Costly"], "answer": "Safe storage" },
{ "id": 268, "chapter": "HOTS", "question": "Why is digital payment growing?", "options": ["Slow", "Convenient", "Expensive", "Risky"], "answer": "Convenient" },
{ "id": 269, "chapter": "HOTS", "question": "Why is inflation controlled?", "options": ["To increase price", "To stabilize economy", "To reduce trade", "None"], "answer": "To stabilize economy" },
{ "id": 270, "chapter": "HOTS", "question": "Why sustainable development is needed?", "options": ["Overuse", "Future safety", "Waste", "None"], "answer": "Future safety" },
{ "id": 271, "chapter": "Application", "question": "A coastal city avoids extreme heat. Factor?", "options": ["Altitude", "Sea influence", "Wind", "Rain"], "answer": "Sea influence" },
{ "id": 272, "chapter": "Application", "question": "A desert farmer grows cactus. Why?", "options": ["High rainfall", "Dry climate", "Cold", "Wind"], "answer": "Dry climate" },
{ "id": 273, "chapter": "Application", "question": "A buyer checks expiry date. Which right?", "options": ["Choice", "Information", "Safety", "Redressal"], "answer": "Information" },
{ "id": 274, "chapter": "Application", "question": "A bank reduces interest rate. Impact?", "options": ["Less loans", "More loans", "No change", "Loss"], "answer": "More loans" },
{ "id": 275, "chapter": "Application", "question": "Heavy rains cause flood. Solution?", "options": ["Deforestation", "Drainage system", "Pollution", "None"], "answer": "Drainage system" },
{ "id": 276, "chapter": "Application", "question": "A cyclone hits coast. Expected damage?", "options": ["No effect", "Flood & wind damage", "Snow", "Heat"], "answer": "Flood & wind damage" },
{ "id": 277, "chapter": "Application", "question": "A tundra region has low farming. Why?", "options": ["Cold soil", "High rainfall", "Heat", "Wind"], "answer": "Cold soil" },
{ "id": 278, "chapter": "Application", "question": "A consumer buys cheap unsafe product. Which right ignored?", "options": ["Safety", "Choice", "Information", "Redressal"], "answer": "Safety" },
{ "id": 279, "chapter": "Application", "question": "A rise in CO2 increases:", "options": ["Cooling", "Global warming", "Rainfall", "Wind"], "answer": "Global warming" },
{ "id": 280, "chapter": "Application", "question": "A bank collapse affects:", "options": ["Weather", "Economy", "Climate", "Wind"], "answer": "Economy" },
{ "id": 281, "chapter": "Revision", "question": "Which climate has highest rainfall?", "options": ["Desert", "Equatorial", "Tundra", "Savanna"], "answer": "Equatorial" },
{ "id": 282, "chapter": "Revision", "question": "Which region is driest?", "options": ["Equatorial", "Desert", "Savanna", "Tundra"], "answer": "Desert" },
{ "id": 283, "chapter": "Revision", "question": "Which system protects consumers?", "options": ["Bank", "Consumer forum", "School", "Police"], "answer": "Consumer forum" },
{ "id": 284, "chapter": "Revision", "question": "Which sector uses money most?", "options": ["Economy", "Weather", "Climate", "Wind"], "answer": "Economy" },
{ "id": 285, "chapter": "Revision", "question": "Which is main greenhouse gas?", "options": ["Oxygen", "CO2", "Nitrogen", "Hydrogen"], "answer": "CO2" },
{ "id": 286, "chapter": "Revision", "question": "Which region is coldest?", "options": ["Desert", "Tundra", "Savanna", "Equatorial"], "answer": "Tundra" },
{ "id": 287, "chapter": "Revision", "question": "Which wind causes monsoon?", "options": ["Trade wind", "Seasonal wind", "Polar wind", "Local wind"], "answer": "Seasonal wind" },
{ "id": 288, "chapter": "Revision", "question": "Which rainfall occurs in mountains?", "options": ["Cyclonic", "Orographic", "Convectional", "None"], "answer": "Orographic" },
{ "id": 289, "chapter": "Revision", "question": "Which payment is digital?", "options": ["Cash", "UPI", "Gold", "Barter"], "answer": "UPI" },
{ "id": 290, "chapter": "Revision", "question": "Which institution controls money supply?", "options": ["SBI", "RBI", "ICICI", "PNB"], "answer": "RBI" },
{ "id": 291, "chapter": "Final", "question": "Main aim of sustainable development?", "options": ["Overuse", "Future safety", "Waste", "Pollution"], "answer": "Future safety" },
{ "id": 292, "chapter": "Final", "question": "Climate change mainly due to:", "options": ["Natural only", "Human only", "Both", "None"], "answer": "Both" },
{ "id": 293, "chapter": "Final", "question": "Best way to save environment?", "options": ["Deforestation", "Conservation", "Pollution", "Overuse"], "answer": "Conservation" },
{ "id": 294, "chapter": "Final", "question": "Main cause of global warming?", "options": ["CO2", "Oxygen", "Nitrogen", "Helium"], "answer": "CO2" },
{ "id": 295, "chapter": "Final", "question": "Which region has grassland?", "options": ["Savanna", "Desert", "Tundra", "Polar"], "answer": "Savanna" },
{ "id": 296, "chapter": "Final", "question": "Which climate has evergreen forest?", "options": ["Equatorial", "Desert", "Savanna", "Tundra"], "answer": "Equatorial" },
{ "id": 297, "chapter": "Final", "question": "Which economic tool replaced barter?", "options": ["Gold", "Money", "Trade", "Bank"], "answer": "Money" },
{ "id": 298, "chapter": "Final", "question": "Which right helps to get compensation?", "options": ["Safety", "Choice", "Redressal", "Information"], "answer": "Redressal" },
{ "id": 299, "chapter": "Final", "question": "Which factor affects wind direction?", "options": ["Humidity", "Coriolis force", "Rainfall", "Clouds"], "answer": "Coriolis force" },
{ "id": 300, "chapter": "Final", "question": "Ultimate goal of development?", "options": ["Profit", "Sustainability", "Growth only", "Trade"], "answer": "Sustainability" }
];

async function seedSocialScience2SSLC() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('Connected to MongoDB');

        const parsedQuestions = [];
        for (let item of rawData) {
            const correctIndex = item.options.indexOf(item.answer);
            parsedQuestions.push({
                question: item.question,
                options: item.options,
                correctIndex: correctIndex !== -1 ? correctIndex : 0,
                level: 1,
                board: "Kerala State",
                class: "10th (SSLC)",
                subject: "Social Science II",
                chapter: item.chapter,
                medium: "English"
            });
        }

        for (const q of parsedQuestions) {
            const exists = await Question.findOne({
                question: q.question,
                subject: q.subject,
                medium: q.medium,
                board: q.board,
                class: q.class
            });

            if (!exists) {
                await Question.create(q);
                console.log(`Added: [${q.medium}] ${q.question.substring(0, 40)}...`);
            } else {
                console.log(`Skipped (Duplicate): [${q.medium}] ${q.question.substring(0, 40)}...`);
            }
        }

        console.log('Social Science II SSLC seeding completed successfully!');
    } catch (error) {
        console.error('Error seeding data:', error);
    } finally {
        await mongoose.disconnect();
    }
}

seedSocialScience2SSLC();
