require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./models/Question');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/quiz-app';

// =============================================
// SSLC SOCIAL SCIENCE I - ENGLISH MEDIUM
// Full 300 Questions
// =============================================

const rawData = [
  { "id": 1, "chapter": "Humanism", "question": "What does the concept of humanism primarily emphasize?", "options": ["Religion", "Human-centered thought", "Nation", "Wealth"], "answer": "Human-centered thought" },
  { "id": 2, "chapter": "Humanism", "question": "What was the central idea of the Renaissance?", "options": ["Religious supremacy", "Man", "King", "Army"], "answer": "Man" },
  { "id": 3, "chapter": "Humanism", "question": "Where did the Renaissance begin?", "options": ["England", "Italy", "France", "Germany"], "answer": "Italy" },
  { "id": 4, "chapter": "Humanism", "question": "What does Renaissance mean?", "options": ["War", "Rebirth", "Trade", "Diplomacy"], "answer": "Rebirth" },
  { "id": 5, "chapter": "Humanism", "question": "Which value did humanism promote?", "options": ["Fear", "Rational thinking", "Superstition", "War"], "answer": "Rational thinking" },
  { "id": 6, "chapter": "Liberty Equality Fraternity", "question": "What was the slogan of the French Revolution?", "options": ["Liberty only", "Equality only", "Liberty, Equality, Fraternity", "Monarchy"], "answer": "Liberty, Equality, Fraternity" },
  { "id": 7, "chapter": "Liberty Equality Fraternity", "question": "In which year did the French Revolution take place?", "options": ["1776", "1789", "1800", "1857"], "answer": "1789" },
  { "id": 8, "chapter": "Liberty Equality Fraternity", "question": "What did the attack on the Bastille mark the beginning of?", "options": ["War", "Revolution", "Trade", "Law"], "answer": "Revolution" },
  { "id": 9, "chapter": "Liberty Equality Fraternity", "question": "Who ended monarchy in France?", "options": ["The people", "The king", "The army", "Farmers"], "answer": "The people" },
  { "id": 10, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution promote?", "options": ["Invasion", "Democracy", "War", "Fear"], "answer": "Democracy" },
  { "id": 11, "chapter": "Social Analysis", "question": "What does sociology study?", "options": ["Individual only", "Society", "Country", "Climate"], "answer": "Society" },
  { "id": 12, "chapter": "Social Analysis", "question": "What is used to study social problems?", "options": ["Belief", "Scientific approach", "Fear", "Opinion"], "answer": "Scientific approach" },
  { "id": 13, "chapter": "Social Analysis", "question": "What does inequality in society indicate?", "options": ["Equality", "Difference", "Peace", "Growth"], "answer": "Difference" },
  { "id": 14, "chapter": "Social Analysis", "question": "What is the main element of society?", "options": ["King", "Individual", "Army", "Trade"], "answer": "Individual" },
  { "id": 15, "chapter": "Social Analysis", "question": "Through what does social change occur?", "options": ["Stability", "Development", "Neglect", "Fear"], "answer": "Development" },
  { "id": 16, "chapter": "Wealth and the World", "question": "What is wealth?", "options": ["Money only", "Useful things", "Land", "House"], "answer": "Useful things" },
  { "id": 17, "chapter": "Wealth and the World", "question": "What is production?", "options": ["Buying", "Production", "Distribution", "Selling"], "answer": "Production" },
  { "id": 18, "chapter": "Wealth and the World", "question": "What are the main components of an economy?", "options": ["Trade", "Production", "Distribution", "All"], "answer": "All" },
  { "id": 19, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local trade", "Global connection", "War", "Governance"], "answer": "Global connection" },
  { "id": 20, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["House", "Place of sale", "Country", "Town"], "answer": "Place of sale" },
  { "id": 21, "chapter": "Public Opinion in Democracy", "question": "What is most important in democracy?", "options": ["King", "People", "Army", "Law"], "answer": "People" },
  { "id": 22, "chapter": "Public Opinion in Democracy", "question": "How is public opinion formed?", "options": ["Media", "Discussions", "Education", "All"], "answer": "All" },
  { "id": 23, "chapter": "Public Opinion in Democracy", "question": "What is the role of media?", "options": ["News", "Opinion formation", "Education", "All"], "answer": "All" },
  { "id": 24, "chapter": "Public Opinion in Democracy", "question": "What is voting right?", "options": ["Right", "Duty", "Trade", "Law"], "answer": "Right" },
  { "id": 25, "chapter": "Public Opinion in Democracy", "question": "What is needed for democracy to survive?", "options": ["Fear", "Active citizens", "War", "Control"], "answer": "Active citizens" },
  { "id": 26, "chapter": "Freedom Struggle", "question": "Who was the leader of the Indian Freedom Struggle?", "options": ["Nehru", "Gandhiji", "Bose", "Tilak"], "answer": "Gandhiji" },
  { "id": 27, "chapter": "Freedom Struggle", "question": "Who started Satyagraha?", "options": ["Nehru", "Gandhi", "Bose", "Rajaji"], "answer": "Gandhi" },
  { "id": 28, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Peace", "Non-violence", "War"], "answer": "Non-violence" },
  { "id": 29, "chapter": "Freedom Struggle", "question": "What is the Champaran Satyagraha related to?", "options": ["Salt", "Indigo cultivation", "Trade", "Education"], "answer": "Indigo cultivation" },
  { "id": 30, "chapter": "Freedom Struggle", "question": "In which year did India get freedom?", "options": ["1945", "1947", "1950", "1930"], "answer": "1947" },
  { "id": 31, "chapter": "Freedom Struggle", "question": "Which section was the Ahmedabad strike related to?", "options": ["Farmers", "Workers", "Students", "Traders"], "answer": "Workers" },
  { "id": 32, "chapter": "Freedom Struggle", "question": "In which state did the Kheda Satyagraha take place?", "options": ["Bihar", "Gujarat", "Kerala", "Punjab"], "answer": "Gujarat" },
  { "id": 33, "chapter": "Freedom Struggle", "question": "Where did Gandhiji get his political training?", "options": ["India", "South Africa", "England", "America"], "answer": "South Africa" },
  { "id": 34, "chapter": "Freedom Struggle", "question": "What is the basic principle of Satyagraha?", "options": ["Violence", "Truth", "Fear", "War"], "answer": "Truth" },
  { "id": 35, "chapter": "Freedom Struggle", "question": "What is the importance of Ahimsa?", "options": ["Violence", "Peace", "War", "Fear"], "answer": "Peace" },
  { "id": 36, "chapter": "Freedom Struggle", "question": "In which year was the Indian National Congress formed?", "options": ["1885", "1905", "1919", "1857"], "answer": "1885" },
  { "id": 37, "chapter": "Freedom Struggle", "question": "What was Gandhiji's first major satyagraha in India?", "options": ["Dandi March", "Champaran", "Kheda", "Quit India"], "answer": "Champaran" },
  { "id": 38, "chapter": "Freedom Struggle", "question": "What was the aim of the Dandi March?", "options": ["Land", "Salt Law", "Trade", "Education"], "answer": "Salt Law" },
  { "id": 39, "chapter": "Freedom Struggle", "question": "When did the Quit India Movement take place?", "options": ["1919", "1930", "1942", "1947"], "answer": "1942" },
  { "id": 40, "chapter": "Freedom Struggle", "question": "What was the role of women in the freedom struggle?", "options": ["None", "Less", "Very important", "Unimportant"], "answer": "Very important" },
  { "id": 41, "chapter": "Independent India", "question": "When did the Constitution of India come into force?", "options": ["1947", "1950", "1949", "1952"], "answer": "1950" },
  { "id": 42, "chapter": "Independent India", "question": "What does the Preamble of the Constitution declare?", "options": ["Laws", "Values", "Trade", "War"], "answer": "Values" },
  { "id": 43, "chapter": "Independent India", "question": "What is democracy?", "options": ["Monarchy", "Rule by the people", "Military rule", "Control"], "answer": "Rule by the people" },
  { "id": 44, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Law"], "answer": "Secularism" },
  { "id": 45, "chapter": "Independent India", "question": "What is the major right given by the Constitution?", "options": ["Trade", "Fundamental Rights", "War", "Wealth"], "answer": "Fundamental Rights" },
  { "id": 46, "chapter": "Democracy", "question": "What is the basis of democracy?", "options": ["King", "People", "Army", "Law"], "answer": "People" },
  { "id": 47, "chapter": "Democracy", "question": "Why is voting right important?", "options": ["Fear", "To choose government", "Trade", "War"], "answer": "To choose government" },
  { "id": 48, "chapter": "Democracy", "question": "What is the job of the Election Commission?", "options": ["Law", "Conduct elections", "Trade", "Army"], "answer": "Conduct elections" },
  { "id": 49, "chapter": "Democracy", "question": "What is a major value in democracy?", "options": ["Fear", "Equality", "War", "Control"], "answer": "Equality" },
  { "id": 50, "chapter": "Democracy", "question": "In democracy, power belongs to whom?", "options": ["King", "People", "Army", "Court"], "answer": "People" },
  { "id": 51, "chapter": "Social Structure", "question": "What is society?", "options": ["Individual", "Organized human beings", "Country", "War"], "answer": "Organized human beings" },
  { "id": 52, "chapter": "Social Structure", "question": "Example of social institutions?", "options": ["Family", "School", "Religion", "All"], "answer": "All" },
  { "id": 53, "chapter": "Social Structure", "question": "What causes social change?", "options": ["Education", "Technology", "Development", "All"], "answer": "All" },
  { "id": 54, "chapter": "Social Structure", "question": "Main role of family?", "options": ["Education", "Transmission of culture", "Trade", "Law"], "answer": "Transmission of culture" },
  { "id": 55, "chapter": "Social Structure", "question": "What causes inequality in society?", "options": ["Equality", "Differences", "Peace", "Development"], "answer": "Differences" },
  { "id": 56, "chapter": "Social Structure", "question": "What is social integration?", "options": ["Separation", "Working together", "War", "Fear"], "answer": "Working together" },
  { "id": 57, "chapter": "Social Structure", "question": "Main element of society?", "options": ["King", "Individual", "Army", "Trade"], "answer": "Individual" },
  { "id": 58, "chapter": "Social Structure", "question": "What does social relationship indicate?", "options": ["Relationship between individuals", "Country", "Trade", "Law"], "answer": "Relationship between individuals" },
  { "id": 59, "chapter": "Social Structure", "question": "What is needed to solve social problems?", "options": ["Fear", "Education", "Neglect", "War"], "answer": "Education" },
  { "id": 60, "chapter": "Social Structure", "question": "What does the progress of society depend on?", "options": ["Fear", "Education", "War", "Control"], "answer": "Education" },
  { "id": 61, "chapter": "Humanism", "question": "What was the major change during the Renaissance period?", "options": ["Religious supremacy", "Human-centered thought", "Monarchy", "War"], "answer": "Human-centered thought" },
  { "id": 62, "chapter": "Humanism", "question": "Which period promoted rational thinking?", "options": ["Middle Ages", "Renaissance", "Ancient period", "Modern period"], "answer": "Renaissance" },
  { "id": 63, "chapter": "Humanism", "question": "Greco-Roman cultures are known as?", "options": ["Modern", "Classical", "New", "Regional"], "answer": "Classical" },
  { "id": 64, "chapter": "Humanism", "question": "What was the main result of the Renaissance?", "options": ["Superstition", "Scientific development", "War", "Weakness"], "answer": "Scientific development" },
  { "id": 65, "chapter": "Humanism", "question": "Which idea gave importance to human freedom?", "options": ["Religion", "Humanism", "Monarchy", "War"], "answer": "Humanism" },
  { "id": 66, "chapter": "Liberty Equality Fraternity", "question": "The French Revolution took place in which country?", "options": ["Italy", "France", "Germany", "England"], "answer": "France" },
  { "id": 67, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution oppose?", "options": ["People", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 68, "chapter": "Liberty Equality Fraternity", "question": "What is equality?", "options": ["Difference", "Equal rights", "Fear", "War"], "answer": "Equal rights" },
  { "id": 69, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Control", "Rights", "Fear", "War"], "answer": "Rights" },
  { "id": 70, "chapter": "Liberty Equality Fraternity", "question": "What does fraternity indicate?", "options": ["Division", "Unity", "War", "Fear"], "answer": "Unity" },
  { "id": 71, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 72, "chapter": "Wealth and the World", "question": "What is a market economy?", "options": ["Selling", "Buying and selling system", "War", "Law"], "answer": "Buying and selling system" },
  { "id": 73, "chapter": "Wealth and the World", "question": "What is distribution?", "options": ["Production", "Distribution of goods", "Buying", "War"], "answer": "Distribution of goods" },
  { "id": 74, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Selling", "Use", "Buying", "Distribution"], "answer": "Use" },
  { "id": 75, "chapter": "Wealth and the World", "question": "What does globalisation promote?", "options": ["Local", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 76, "chapter": "Public Opinion", "question": "What plays a major role in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 77, "chapter": "Public Opinion", "question": "What is freedom of expression in democracy?", "options": ["Control", "Freedom", "Fear", "War"], "answer": "Freedom" },
  { "id": 78, "chapter": "Public Opinion", "question": "What do the media provide?", "options": ["News", "Information", "Opinion", "All"], "answer": "All" },
  { "id": 79, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 80, "chapter": "Public Opinion", "question": "What is an active citizen?", "options": ["One who does not vote", "One who participates", "One who fears", "One who neglects"], "answer": "One who participates" },
  { "id": 81, "chapter": "Freedom Struggle", "question": "Another name for Satyagraha?", "options": ["Violence", "Non-violent struggle", "War", "Control"], "answer": "Non-violent struggle" },
  { "id": 82, "chapter": "Freedom Struggle", "question": "Which value did Gandhiji promote?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 83, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 84, "chapter": "Freedom Struggle", "question": "What method did Gandhiji use?", "options": ["Violence", "Satyagraha", "War", "Control"], "answer": "Satyagraha" },
  { "id": 85, "chapter": "Freedom Struggle", "question": "What was the Indian freedom struggle mainly for?", "options": ["Trade", "Freedom", "War", "Fear"], "answer": "Freedom" },
  { "id": 86, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 87, "chapter": "Independent India", "question": "What ensures equality?", "options": ["Law", "Government", "War", "Trade"], "answer": "Law" },
  { "id": 88, "chapter": "Independent India", "question": "What is a major value included in the Constitution?", "options": ["Fear", "Equality", "War", "Control"], "answer": "Equality" },
  { "id": 89, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 90, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 91, "chapter": "Humanism", "question": "What is the main feature of the Renaissance?", "options": ["Religious supremacy", "Rational thinking", "War", "Monarchy"], "answer": "Rational thinking" },
  { "id": 92, "chapter": "Humanism", "question": "In which fields did the Renaissance bring changes?", "options": ["Art", "Science", "Culture", "All"], "answer": "All" },
  { "id": 93, "chapter": "Humanism", "question": "What value developed during the Renaissance?", "options": ["Superstition", "Freedom", "Fear", "War"], "answer": "Freedom" },
  { "id": 94, "chapter": "Humanism", "question": "Which thought gave importance to human abilities?", "options": ["Religious thought", "Humanism", "Monarchy", "War"], "answer": "Humanism" },
  { "id": 95, "chapter": "Humanism", "question": "What change did the Renaissance bring to Europe?", "options": ["Superstition", "Scientific thinking", "War", "Monarchy"], "answer": "Scientific thinking" },
  { "id": 96, "chapter": "Liberty Equality Fraternity", "question": "Which rule did the French Revolution end?", "options": ["Democracy", "Monarchy", "Equality", "Religion"], "answer": "Monarchy" },
  { "id": 97, "chapter": "Liberty Equality Fraternity", "question": "Which values did the French Revolution promote?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 98, "chapter": "Liberty Equality Fraternity", "question": "What right did the French Revolution give to the people?", "options": ["Invasion", "Liberty", "War", "Fear"], "answer": "Liberty" },
  { "id": 99, "chapter": "Liberty Equality Fraternity", "question": "What ensures equality?", "options": ["Law", "Fear", "War", "Trade"], "answer": "Law" },
  { "id": 100, "chapter": "Liberty Equality Fraternity", "question": "People's participation is part of which idea?", "options": ["Monarchy", "Democracy", "War", "Control"], "answer": "Democracy" },
  { "id": 101, "chapter": "Wealth and the World", "question": "What is the basic element of economic activities?", "options": ["Trade", "Production", "Distribution", "All"], "answer": "All" },
  { "id": 102, "chapter": "Wealth and the World", "question": "What is the goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 103, "chapter": "Wealth and the World", "question": "What is a major element in market system?", "options": ["Buying", "Selling", "Price", "All"], "answer": "All" },
  { "id": 104, "chapter": "Wealth and the World", "question": "What do we get through globalisation?", "options": ["Global connection", "War", "Fear", "Control"], "answer": "Global connection" },
  { "id": 105, "chapter": "Wealth and the World", "question": "What does consumption depend on?", "options": ["Income", "Need", "Price", "All"], "answer": "All" },
  { "id": 106, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 107, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 108, "chapter": "Public Opinion", "question": "What is the main job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 109, "chapter": "Public Opinion", "question": "What is the role of people in democracy?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 110, "chapter": "Public Opinion", "question": "What should active citizens do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 111, "chapter": "Freedom Struggle", "question": "What was Gandhiji's method of struggle?", "options": ["Violence", "Non-violence", "War", "Control"], "answer": "Non-violence" },
  { "id": 112, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Control", "Fear"], "answer": "To achieve truth" },
  { "id": 113, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 114, "chapter": "Freedom Struggle", "question": "What was the aim of the Indian freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 115, "chapter": "Freedom Struggle", "question": "Which value did Gandhiji promote?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 116, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 117, "chapter": "Independent India", "question": "What is the main aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 118, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 119, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 120, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 121, "chapter": "Humanism", "question": "What does humanism primarily emphasize?", "options": ["Religion", "Human abilities", "Monarchy", "War"], "answer": "Human abilities" },
  { "id": 122, "chapter": "Humanism", "question": "What thought did the Renaissance promote?", "options": ["Superstition", "Rational thinking", "Fear", "War"], "answer": "Rational thinking" },
  { "id": 123, "chapter": "Humanism", "question": "In which country did the Renaissance begin?", "options": ["France", "Italy", "Germany", "England"], "answer": "Italy" },
  { "id": 124, "chapter": "Humanism", "question": "What resulted from the Renaissance?", "options": ["Scientific progress", "Superstition", "War", "Monarchy"], "answer": "Scientific progress" },
  { "id": 125, "chapter": "Humanism", "question": "Which idea gives importance to human freedom?", "options": ["Religion", "Humanism", "Monarchy", "Control"], "answer": "Humanism" },
  { "id": 126, "chapter": "Liberty Equality Fraternity", "question": "In which year did the French Revolution take place?", "options": ["1776", "1789", "1857", "1947"], "answer": "1789" },
  { "id": 127, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution oppose?", "options": ["Democracy", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 128, "chapter": "Liberty Equality Fraternity", "question": "What is the slogan of the French Revolution?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 129, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Rights", "Fear", "War", "Control"], "answer": "Rights" },
  { "id": 130, "chapter": "Liberty Equality Fraternity", "question": "What ensures equality?", "options": ["Law", "War", "Fear", "Trade"], "answer": "Law" },
  { "id": 131, "chapter": "Wealth and the World", "question": "What is the main goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 132, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 133, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["Place of sale", "Country", "House", "War"], "answer": "Place of sale" },
  { "id": 134, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local trade", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 135, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Use", "Selling", "Buying", "Distribution"], "answer": "Use" },
  { "id": 136, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 137, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 138, "chapter": "Public Opinion", "question": "What is the job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 139, "chapter": "Public Opinion", "question": "What is the role of people?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 140, "chapter": "Public Opinion", "question": "What should an active citizen do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 141, "chapter": "Freedom Struggle", "question": "What was Gandhiji's method of struggle?", "options": ["Violence", "Non-violence", "War", "Control"], "answer": "Non-violence" },
  { "id": 142, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Fear", "Control"], "answer": "To achieve truth" },
  { "id": 143, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 144, "chapter": "Freedom Struggle", "question": "What was the aim of the freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 145, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 146, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 147, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 148, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 149, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 150, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 151, "chapter": "Humanism", "question": "What is the main value promoted by the Renaissance?", "options": ["Superstition", "Rational thinking", "War", "Monarchy"], "answer": "Rational thinking" },
  { "id": 152, "chapter": "Humanism", "question": "What change occurred as a result of the Renaissance?", "options": ["Scientific development", "Superstition", "War", "Fear"], "answer": "Scientific development" },
  { "id": 153, "chapter": "Humanism", "question": "What is the basic idea of humanism?", "options": ["Religion", "Man", "King", "War"], "answer": "Man" },
  { "id": 154, "chapter": "Humanism", "question": "Where did the Renaissance begin?", "options": ["France", "Italy", "Germany", "England"], "answer": "Italy" },
  { "id": 155, "chapter": "Humanism", "question": "What was the aim of the Renaissance?", "options": ["Religious supremacy", "Human development", "War", "Control"], "answer": "Human development" },
  { "id": 156, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution oppose?", "options": ["Democracy", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 157, "chapter": "Liberty Equality Fraternity", "question": "What was the main idea of the French Revolution?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 158, "chapter": "Liberty Equality Fraternity", "question": "What does equality indicate?", "options": ["Difference", "Equal rights", "War", "Fear"], "answer": "Equal rights" },
  { "id": 159, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Control", "Rights", "War", "Fear"], "answer": "Rights" },
  { "id": 160, "chapter": "Liberty Equality Fraternity", "question": "What does fraternity indicate?", "options": ["Division", "Unity", "War", "Fear"], "answer": "Unity" },
  { "id": 161, "chapter": "Wealth and the World", "question": "What is the goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 162, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 163, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["Place of sale", "Country", "House", "War"], "answer": "Place of sale" },
  { "id": 164, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 165, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Use", "Selling", "Buying", "Distribution"], "answer": "Use" },
  { "id": 166, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 167, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 168, "chapter": "Public Opinion", "question": "What is the job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 169, "chapter": "Public Opinion", "question": "What is the role of people?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 170, "chapter": "Public Opinion", "question": "What should an active citizen do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 171, "chapter": "Freedom Struggle", "question": "What was Gandhiji's method of struggle?", "options": ["Violence", "Non-violence", "War", "Control"], "answer": "Non-violence" },
  { "id": 172, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Fear", "Control"], "answer": "To achieve truth" },
  { "id": 173, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 174, "chapter": "Freedom Struggle", "question": "What was the aim of the freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 175, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 176, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 177, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 178, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 179, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 180, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 181, "chapter": "Humanism", "question": "What ability of man did the Renaissance uplift?", "options": ["Superstition", "Power of thinking", "Power of war", "Fear"], "answer": "Power of thinking" },
  { "id": 182, "chapter": "Humanism", "question": "Which major area grew during the Renaissance?", "options": ["Science", "Art", "Literature", "All"], "answer": "All" },
  { "id": 183, "chapter": "Humanism", "question": "Which period gave importance to rational thinking?", "options": ["Middle Ages", "Renaissance", "Ancient period", "Modern period"], "answer": "Renaissance" },
  { "id": 184, "chapter": "Humanism", "question": "Which thought is centered on man?", "options": ["Religious thought", "Humanism", "Monarchy", "War"], "answer": "Humanism" },
  { "id": 185, "chapter": "Humanism", "question": "What was the main result of the Renaissance?", "options": ["Superstition", "Scientific progress", "War", "Fear"], "answer": "Scientific progress" },
  { "id": 186, "chapter": "Liberty Equality Fraternity", "question": "Which rule did the French Revolution oppose?", "options": ["Democracy", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 187, "chapter": "Liberty Equality Fraternity", "question": "What were the main values of the French Revolution?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 188, "chapter": "Liberty Equality Fraternity", "question": "What is equality?", "options": ["Difference", "Equal rights", "Fear", "War"], "answer": "Equal rights" },
  { "id": 189, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Control", "Rights", "Fear", "War"], "answer": "Rights" },
  { "id": 190, "chapter": "Liberty Equality Fraternity", "question": "What does fraternity indicate?", "options": ["Division", "Unity", "War", "Fear"], "answer": "Unity" },
  { "id": 191, "chapter": "Wealth and the World", "question": "What is the goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 192, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 193, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["Place of sale", "Country", "House", "War"], "answer": "Place of sale" },
  { "id": 194, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 195, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Use", "Selling", "Buying", "Distribution"], "answer": "Use" },
  { "id": 196, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 197, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 198, "chapter": "Public Opinion", "question": "What is the job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 199, "chapter": "Public Opinion", "question": "What is the role of people?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 200, "chapter": "Public Opinion", "question": "What should an active citizen do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 201, "chapter": "Freedom Struggle", "question": "What was Gandhiji's method of struggle?", "options": ["Violence", "Non-violence", "War", "Control"], "answer": "Non-violence" },
  { "id": 202, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Fear", "Control"], "answer": "To achieve truth" },
  { "id": 203, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 204, "chapter": "Freedom Struggle", "question": "What was the aim of the freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 205, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 206, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 207, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 208, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 209, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 210, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 211, "chapter": "Humanism", "question": "What thought grew during the Renaissance?", "options": ["Superstition", "Rational thinking", "War", "Monarchy"], "answer": "Rational thinking" },
  { "id": 212, "chapter": "Humanism", "question": "Which thought gave importance to human abilities?", "options": ["Religious thought", "Humanism", "Monarchy", "War"], "answer": "Humanism" },
  { "id": 213, "chapter": "Humanism", "question": "What was the main result of the Renaissance?", "options": ["Scientific progress", "Superstition", "War", "Fear"], "answer": "Scientific progress" },
  { "id": 214, "chapter": "Humanism", "question": "In which country did the Renaissance begin?", "options": ["France", "Italy", "Germany", "England"], "answer": "Italy" },
  { "id": 215, "chapter": "Humanism", "question": "What does human-centered thought indicate?", "options": ["Religion", "Man is important", "King", "War"], "answer": "Man is important" },
  { "id": 216, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution oppose?", "options": ["Democracy", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 217, "chapter": "Liberty Equality Fraternity", "question": "What were the main values of the French Revolution?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 218, "chapter": "Liberty Equality Fraternity", "question": "What does equality indicate?", "options": ["Difference", "Equal rights", "War", "Fear"], "answer": "Equal rights" },
  { "id": 219, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Control", "Rights", "War", "Fear"], "answer": "Rights" },
  { "id": 220, "chapter": "Liberty Equality Fraternity", "question": "What does fraternity indicate?", "options": ["Division", "Unity", "War", "Fear"], "answer": "Unity" },
  { "id": 221, "chapter": "Wealth and the World", "question": "What is the goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 222, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 223, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["Place of sale", "Country", "House", "War"], "answer": "Place of sale" },
  { "id": 224, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 225, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Use", "Selling", "Buying", "Distribution"], "answer": "Use" },
  { "id": 226, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 227, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 228, "chapter": "Public Opinion", "question": "What is the job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 229, "chapter": "Public Opinion", "question": "What is the role of people?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 230, "chapter": "Public Opinion", "question": "What should an active citizen do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 231, "chapter": "Freedom Struggle", "question": "Which value did Gandhiji promote?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 232, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Fear", "Control"], "answer": "To achieve truth" },
  { "id": 233, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 234, "chapter": "Freedom Struggle", "question": "What was the aim of the freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 235, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 236, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 237, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 238, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 239, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 240, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 241, "chapter": "Humanism", "question": "What is the central idea of humanism?", "options": ["Religion", "Man", "King", "War"], "answer": "Man" },
  { "id": 242, "chapter": "Humanism", "question": "What value did the Renaissance promote?", "options": ["Superstition", "Rational thinking", "Fear", "War"], "answer": "Rational thinking" },
  { "id": 243, "chapter": "Humanism", "question": "Where did the Renaissance begin?", "options": ["France", "Italy", "Germany", "England"], "answer": "Italy" },
  { "id": 244, "chapter": "Humanism", "question": "What was the result of the Renaissance?", "options": ["Scientific progress", "Superstition", "War", "Fear"], "answer": "Scientific progress" },
  { "id": 245, "chapter": "Humanism", "question": "Which thought gave importance to human abilities?", "options": ["Religious thought", "Humanism", "Monarchy", "War"], "answer": "Humanism" },
  { "id": 246, "chapter": "Liberty Equality Fraternity", "question": "What did the French Revolution oppose?", "options": ["Democracy", "Monarchy", "Equality", "Education"], "answer": "Monarchy" },
  { "id": 247, "chapter": "Liberty Equality Fraternity", "question": "What were the main values of the French Revolution?", "options": ["Liberty", "Equality", "Fraternity", "All"], "answer": "All" },
  { "id": 248, "chapter": "Liberty Equality Fraternity", "question": "What is equality?", "options": ["Difference", "Equal rights", "War", "Fear"], "answer": "Equal rights" },
  { "id": 249, "chapter": "Liberty Equality Fraternity", "question": "What does liberty give?", "options": ["Control", "Rights", "War", "Fear"], "answer": "Rights" },
  { "id": 250, "chapter": "Liberty Equality Fraternity", "question": "What does fraternity indicate?", "options": ["Division", "Unity", "War", "Fear"], "answer": "Unity" },
  { "id": 251, "chapter": "Wealth and the World", "question": "What is the goal of an economy?", "options": ["Profit", "Satisfying human needs", "War", "Control"], "answer": "Satisfying human needs" },
  { "id": 252, "chapter": "Wealth and the World", "question": "What are the factors of production?", "options": ["Land", "Labour", "Capital", "All"], "answer": "All" },
  { "id": 253, "chapter": "Wealth and the World", "question": "What is a market?", "options": ["Place of sale", "Country", "House", "War"], "answer": "Place of sale" },
  { "id": 254, "chapter": "Wealth and the World", "question": "What is globalisation?", "options": ["Local", "Global connection", "War", "Control"], "answer": "Global connection" },
  { "id": 255, "chapter": "Wealth and the World", "question": "What is consumption?", "options": ["Use", "Selling", "Buying", "Distribution"], "answer": "Use" },
  { "id": 256, "chapter": "Public Opinion", "question": "What helps in forming public opinion?", "options": ["Media", "Education", "Society", "All"], "answer": "All" },
  { "id": 257, "chapter": "Public Opinion", "question": "What is a major right in democracy?", "options": ["Voting right", "War", "Fear", "Control"], "answer": "Voting right" },
  { "id": 258, "chapter": "Public Opinion", "question": "What is the job of media?", "options": ["Giving information", "Forming opinion", "Education", "All"], "answer": "All" },
  { "id": 259, "chapter": "Public Opinion", "question": "What is the role of people?", "options": ["Unimportant", "Important", "None", "Less"], "answer": "Important" },
  { "id": 260, "chapter": "Public Opinion", "question": "What should an active citizen do?", "options": ["Vote", "Participate in discussions", "Create awareness", "All"], "answer": "All" },
  { "id": 261, "chapter": "Freedom Struggle", "question": "What was Gandhiji's method of struggle?", "options": ["Violence", "Non-violence", "War", "Control"], "answer": "Non-violence" },
  { "id": 262, "chapter": "Freedom Struggle", "question": "What is the aim of Satyagraha?", "options": ["To achieve truth", "War", "Fear", "Control"], "answer": "To achieve truth" },
  { "id": 263, "chapter": "Freedom Struggle", "question": "Who fought against British rule?", "options": ["Indians", "British", "Army", "Traders"], "answer": "Indians" },
  { "id": 264, "chapter": "Freedom Struggle", "question": "What was the aim of the freedom struggle?", "options": ["Wealth", "Freedom", "War", "Control"], "answer": "Freedom" },
  { "id": 265, "chapter": "Freedom Struggle", "question": "What is the meaning of Ahimsa?", "options": ["Violence", "Non-violence", "War", "Fear"], "answer": "Non-violence" },
  { "id": 266, "chapter": "Independent India", "question": "What is the main objective of the Constitution?", "options": ["Control", "Justice", "War", "Fear"], "answer": "Justice" },
  { "id": 267, "chapter": "Independent India", "question": "What is the aim of democracy?", "options": ["Government", "Public welfare", "War", "Control"], "answer": "Public welfare" },
  { "id": 268, "chapter": "Independent India", "question": "What rights does the Constitution give?", "options": ["Fundamental Rights", "Trade", "War", "Fear"], "answer": "Fundamental Rights" },
  { "id": 269, "chapter": "Independent India", "question": "What is the source of the Constitution?", "options": ["King", "People", "Army", "Trade"], "answer": "People" },
  { "id": 270, "chapter": "Independent India", "question": "What is secularism?", "options": ["Religious supremacy", "Secularism", "War", "Control"], "answer": "Secularism" },
  { "id": 271, "chapter": "Democracy", "question": "What is the basis of democracy?", "options": ["King", "People", "Army", "Law"], "answer": "People" },
  { "id": 272, "chapter": "Democracy", "question": "Why is voting right important?", "options": ["Fear", "To choose government", "Trade", "War"], "answer": "To choose government" },
  { "id": 273, "chapter": "Democracy", "question": "What is the job of the Election Commission?", "options": ["Conduct elections", "Trade", "War", "Control"], "answer": "Conduct elections" },
  { "id": 274, "chapter": "Democracy", "question": "What is a major value in democracy?", "options": ["Equality", "Fear", "War", "Control"], "answer": "Equality" },
  { "id": 275, "chapter": "Democracy", "question": "In democracy, power belongs to whom?", "options": ["King", "People", "Army", "Court"], "answer": "People" },
  { "id": 276, "chapter": "Social Structure", "question": "What is society?", "options": ["Individual", "Organized human beings", "Country", "War"], "answer": "Organized human beings" },
  { "id": 277, "chapter": "Social Structure", "question": "Example of social institutions?", "options": ["Family", "School", "Religion", "All"], "answer": "All" },
  { "id": 278, "chapter": "Social Structure", "question": "What causes social change?", "options": ["Education", "Technology", "Development", "All"], "answer": "All" },
  { "id": 279, "chapter": "Social Structure", "question": "Main role of family?", "options": ["Transmission of culture", "Trade", "Law", "War"], "answer": "Transmission of culture" },
  { "id": 280, "chapter": "Social Structure", "question": "What is inequality in society?", "options": ["Equality", "Difference", "Peace", "Development"], "answer": "Difference" },
  { "id": 281, "chapter": "Social Structure", "question": "What is social integration?", "options": ["Division", "Working together", "War", "Fear"], "answer": "Working together" },
  { "id": 282, "chapter": "Social Structure", "question": "What is the main element of society?", "options": ["King", "Individual", "Army", "Trade"], "answer": "Individual" },
  { "id": 283, "chapter": "Social Structure", "question": "What does social relationship indicate?", "options": ["Relationship between individuals", "Country", "Trade", "Law"], "answer": "Relationship between individuals" },
  { "id": 284, "chapter": "Social Structure", "question": "What is needed to solve social problems?", "options": ["Education", "Fear", "War", "Neglect"], "answer": "Education" },
  { "id": 285, "chapter": "Social Structure", "question": "What does the progress of society depend on?", "options": ["Education", "War", "Fear", "Control"], "answer": "Education" }
];

async function seedSocialScience1English() {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        let added = 0, skipped = 0;

        for (let item of rawData) {
            const correctIndex = item.options.indexOf(item.answer);

            const q = {
                question: item.question,
                options: item.options,
                correctIndex: correctIndex !== -1 ? correctIndex : 0,
                level: 1,
                board: "Kerala State",
                class: "10th (SSLC)",
                subject: "Social Science I",
                chapter: item.chapter,
                medium: "English"
            };

            const exists = await Question.findOne({
                question: q.question,
                subject: q.subject,
                medium: q.medium,
                board: q.board,
                class: q.class
            });

            if (!exists) {
                await Question.create(q);
                console.log(`✅ Added: ${item.chapter} | ${item.question.substring(0, 50)}...`);
                added++;
            } else {
                console.log(`⏭️ Skipped: ${item.question.substring(0, 50)}...`);
                skipped++;
            }
        }

        console.log(`\n🎉 Seeding completed! Added: ${added} | Skipped: ${skipped}`);

    } catch (error) {
        console.error('❌ Error:', error);
    } finally {
        await mongoose.disconnect();
    }
}

seedSocialScience1English();